app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::resource('/','BaseController');
Route::get('/contacts',array('as' => 'contacts', 'uses' => 'BaseController@contacts'));
Route::post('/add-comment',array('as' => 'add.comment', 'uses' => 'BaseController@addComment'));
Route::get('/design',array('as' => 'design', 'uses' => 'BaseController@design'));
Route::get('/polygraphy',array('as' => 'polygraphy', 'uses' => 'BaseController@poly'));
Route::get('/offers',array('as' => 'offers', 'uses' => 'BaseController@offers'));
Route::get('/about',array('as' => 'about', 'uses' => 'BaseController@about'));

Route::group(array('prefix' => 'admin'/*, 'before' => "logged:/admin/login",*/
					), function(){
	Route::resource('pages', 'AdminPagesController',array('except' => array('update')));
	Route::post('pages/update/{sliders}',array('as' => 'admin.pages.update', 'uses' => 'AdminPagesController@update'));
	
	Route::resource('sliders', 'AdminSlidersController',array('except' => array('update','destroy')));	
	Route::post('sliders/update/{sliders}',array('as' => 'admin.sliders.update', 'uses' => 'AdminSlidersController@update'));
	Route::get('sliders/destroy/{slider}',array('as' => 'admin.sliders.destroy', 'uses' => 'AdminSlidersController@destroy'));	
	
	Route::resource('types', 'AdminTypesController');
	
	Route::resource('comments', 'AdminCommentsController',array('except' => array('update','destroy')));
	Route::post('comments/update/{comments}',array('as' => 'admin.comments.update', 'uses' => 'AdminCommentsController@update'));
	Route::get('comments/destroy/{comment}',array('as' => 'admin.comments.destroy', 'uses' => 'AdminCommentsController@destroy'));	

	Route::resource('designs', 'AdminDesignsController',array('except' => array('update','destroy')));
	Route::post('designs/update/{designs}',array('as' => 'admin.designs.update', 'uses' => 'AdminDesignsController@update'));
	Route::get('designs/destroy/{design}',array('as' => 'admin.designs.destroy', 'uses' => 'AdminDesignsController@destroy'));
	Route::post('designs/order-update',array('as' => 'admin.designs.order', 'uses' => 'AdminDesignsController@changeOrderOfDesign'));

	Route::resource('designimgs', 'AdminDesignImgsController',array('except' => array('update','destroy')));	
	Route::post('designimgs/update/{designs}',array('as' => 'admin.designimgs.update', 'uses' => 'AdminDesignImgsController@update'));
	Route::get('designimgs/destroy/{design}',array('as' => 'admin.designimgs.destroy', 'uses' => 'AdminDesignImgsController@destroy'));
	
	Route::resource('polycategories', 'AdminPolyCategoriesController',array('except' => array('update','destroy')));
	Route::post('polycategories/update/{id}',array('as' => 'admin.polycategories.update', 'uses' => 'AdminPolyCategoriesController@update'));
	Route::get('polycategories/destroy/{id}',array('as' => 'admin.polycategories.destroy', 'uses' => 'AdminPolyCategoriesController@destroy'));		
	Route::post('polycategories/order-update',array('as' => 'admin.polycategories.order', 'uses' => 'AdminPolyCategoriesController@changeOrderOfDesign'));	

	Route::resource('polygrafs', 'AdminPolygrafsController',array('except' => array('update','destroy','index')));	
	Route::post('polygrafs/update/{id}',array('as' => 'admin.polygrafs.update', 'uses' => 'AdminPolygrafsController@update'));
	Route::get('polygrafs/destroy/{id}',array('as' => 'admin.polygrafs.destroy', 'uses' => 'AdminPolygrafsController@destroy'));	

	Route::resource('offers', 'AdminOffersController',array('except' => array('update','destroy')));
	Route::post('offers/update/{id}',array('as' => 'admin.offers.update', 'uses' => 'AdminOffersController@update'));
	Route::get('offers/destroy/{id}',array('as' => 'admin.offers.destroy', 'uses' => 'AdminOffersController@destroy'));		
	
	Route::post('abouts/update/{id}',array('as' => 'admin.abouts.update', 'uses' => 'AdminAboutsController@update'));
	Route::get('abouts',array('as' => 'admin.abouts.edit', 'uses' => 'AdminAboutsController@edit'));	

	Route::resource('teams', 'AdminTeamsController',array('except' => array('update','destroy')));	
	Route::post('teams/update/{id}',array('as' => 'admin.teams.update', 'uses' => 'AdminTeamsController@update'));
	Route::get('teams/destroy/{id}',array('as' => 'admin.teams.destroy', 'uses' => 'AdminTeamsController@destroy'));	
	Route::post('teams/order-update',array('as' => 'admin.teams.order', 'uses' => 'AdminTeamsController@orderUpdate'));
});

app/models/DesignImg.php
<?php
use Codesleeve\Stapler\ORM\StaplerableInterface;
use Codesleeve\Stapler\ORM\EloquentTrait;

class DesignImg extends \Eloquent implements StaplerableInterface{

	use EloquentTrait;

	// Add your validation rules here
	public static $rules = [
		// 'title' => 'required'
	];

	// Don't forget to fill this array
	protected $fillable = ['img','order','name','description','show','design_id'];

	public function __construct(array $attributes = array()) {
        $this->hasAttachedFile('img', [
            'styles' => [                      
            'thumb' => '280x240'            
            ]
        ]);

        parent::__construct($attributes);
    }

    public function design()
	{
		return $this->belongsTo('Design');
	}

}

app/views/admin/designimgs/create.blade.php
@extends('laravel-authentication-acl::admin.layouts.base-2cols')

@section('title')
Admin area: dashboard
@stop

@section('content')	
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title bariol-thin"><i class="fa fa-pencil"> Новая фотография</i></h3>
            </div>            
            <div class="panel-body">
			{{ Form::open(array('route' => 'admin.designimgs.store','method' => 'post','files' => true))}}
				@include('admin.designimgs._partials.form')
			{{ Form::close()}}	
			</div>
        </div>       
    </div>
</div>	
@stop 

app/views/admin/designimgs/edit.blade.php
@extends('laravel-authentication-acl::admin.layouts.base-2cols')

@section('title')
Admin area: dashboard
@stop
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title bariol-thin"><i class="fa fa-pencil"> {{$designimg->id}}</i></h3>
            </div>            
            <div class="panel-body">
            	<img src="{{ $designimg->img->url('thumb') }}" >
           		{{ Form::model($designimg, array('route' => array('admin.designimgs.update',$designimg->id),'method' => 'post','files' => true))}}
					@include('admin.designimgs._partials.form')
				{{ Form::close()}}	
            </div>
        </div>       
    </div>
</div>	
@stop 

app/views/admin/designimgs/index.blade.php
@extends('laravel-authentication-acl::admin.layouts.base-2cols')

@section('title')
Admin area: dashboard
@stop

@section('content')	
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title bariol-thin"><i class="fa fa-pencil"> Коллекция: {{$design->name}}</i></h3>
            </div>            
            <div class="panel-body">
			<div class="row">
                <div class="col-md-12 margin-bottom-12">
                    <a href="{{URL::route('admin.designimgs.create')}}" class="btn btn-info pull-right"><i class="fa fa-plus"></i> Добавить</a>
                </div>
            </div>
            @if(  count($designimgs) > 0 )
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Название</th>                       
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($designimgs as $designimg)
                        <tr>
                            <td style="width:80%">{{$designimg->name}}</td>                            
                            <td style="witdh:10%">{{$designimg->show ? '<i class="fa fa-eye"></i>' : ''}}</td>
                            <td style="witdh:10%">                               
                                <a href="{{URL::route('admin.designimgs.edit', ['id' => $designimg->id])}}"><i class="fa fa-pencil-square-o fa-2x"></i></a>
                                <a href="{{URL::route('admin.designimgs.destroy',['id' => $designimg->id, '_token' => csrf_token()])}}" class="margin-left-5"><i class="fa fa-trash-o delete fa-2x"></i></a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>                
            @else
            <span class="text-warning"><h5>Нет коллекций.</h5></span>
            @endif
			</div>
        </div>       
    </div>
</div>	
@stop 